In [3]:
import numpy as np
import pandas as pd
from Utils.rum import RUM
import os
from pystata import config
import contextlib
with contextlib.redirect_stdout(None):
    config.init('se')
from pystata import stata
from functools import reduce
from Utils.preprocess import preprocess

In [2]:
data = pd.read_csv('~/OneDrive/Documents/Academics/Data/Bruhin2019/choices_exp1_inclZalloc_inclSubjChar.csv') 

In [5]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
np.sqrt(np.diag(a))

array([1.        , 2.23606798, 3.        ])